### ISSUE TITLE
Multiple sources 

### ISSUE THREAD

**Issue by kmugEq** [equinor/septic-config-generator#167]
Maybe duplicate/overlap of https://github.com/equinor/septic-config-generator/issues/10

Ability for multiple sources. For Gudrun the source is getting quite large and with CSV file it can be cluttered. 

Prefer to have one CSV for stuff, another one for gain scheduling from data analytics etc.

**Comment by einarsi** [comment]
You can already define multiple sources like so:
```yaml
sources:
  - filename: Wells.xlsx
    id: wells
    sheet: Wells
  - templates: Templates.csv
    id: templates
    delimiter: ","
``` 
For each layout-item (a single template file used for iteration), you can reference a single source:
```yaml
  - name: 21_DmmyApplWell.cnfg
    source: wells
```
Is your request covered by the above, or do you require the use of multiple sources per layout item, i.e. something like this:
```yaml
  - name: 21_DmmyApplWell.cnfg
    sources:
    - wells
    - wells_part2
```
If so, we need to discuss further 😬
