### ISSUE TITLE
Conditional combination of csv files

### ISSUE THREAD

**Issue by vetlek** [equinor/septic-config-generator#282]
Useful to select conditionally which files to include. E.g. a set of csv files for initial conditions and selecting which one to use at run time. Initial conditions should be combined with the general information for the wells, lines etc.

**Comment by einarsi** [comment]
How do you want to specify which sources and/or files to use? There are currently two primary source definitions. Single:
```yaml
sources:
  - id: wells
    filename: wells.csv
```
and multiple:
```yaml
sources:
  - id: wells
    filename:
      - wells.csv
      - risers.csv
      - well_tuning_parameters.csv
```
Source file combinations must be selected by specifying global parameters, (e.g. `scg make --var ic 1`). And then we can check the value of those parameters. Please suggest a yaml syntax modification that is appropriate for your use case(s).
